apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content-san-eco
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-block-rwo-eco