kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-from-snap
  labels:
    scenario: clone
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-file-rwx
  dataSource:
    name: blog-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io