---
- name: install epel-release for CentOS
  yum:
    name: epel-release
  when: ansible_distribution == "CentOS"

  # TODO: Verify that RHEL  does not require venv
- name: install openshift python client for k8s_raw module
  yum:
    name: python2-openshift
  when: ansible_os_family == 'RedHat'
  environment: "{{proxy_env if proxy_env is defined else {}}}"