- name: Copy backend config file(s) to control node
  template:
    src: backend.j2
    dest: /root/trident-installer/backend-{{ item.backendName }}.json
  with_items: "{{ backends_to_create }}"
  when: create_backends == true
  run_once: true

- name: Create Trident backend(s)
  command: /root/trident-installer/tridentctl -n trident create backend -f /root/trident-installer/backend-{{ item.backendName }}.json
  with_items: "{{ backends_to_create }}"
  when: create_backends == true
  run_once: true