apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content
  namespace: import
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-file-rwx