apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content-import
  namespace: ghostnas
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-file-rwx