apiVersion: v1
kind: Service
metadata:
  name: blogclone
  labels:
    scenario: clone
spec:
  type: NodePort
  selector:
    app: blogclone
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368
    nodePort: 30081